### PR TITLE
Protect against NaN values of size (in JSDOM for example)

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by jquense** [comment]
thanks for the PR. I'm not sure why js DOM would be NaN here. I don't think the underlying reason is non number widths on jsdom nodes, that would be a pretty glaring jsdom bug if it was

**Comment by pgilad** [comment]
I haven't dug into why this happens, but it does in my tests and I receive a warning about it

**Comment by bookworm2death** [comment]
I'm getting this same error, how do I get around it until this is merged?

**Comment by Sarthakagarwal22** [comment]
i am still getting this warning, is there any way around it

**Pull request closed without merging**
