### PR TITLE
Bundle esm with rollup to track treeshakability with size snapshot

### PR DESCRIPTION
**Pull request by TrySound**
This diff introduces rollup with size snapshot plugin which allows to
track the size of the project and treeshaked size by both rollup and
webpack.

I will make a couple of PRs and you will see when the result will be
achieved.

### CODE REVIEW

**Comment by jquense** [comment]
Traveling, ping me on Tuesday!

**Comment by TrySound** [comment]
@jquense Ping as you asked me.

**Comment by TrySound** [comment]
The problem is that path import approach works bad with differet formats. If we land cjs and esm users will be forced to choose which format they need. This works bad when the code is isomorphic or tested with node so we should do some hacks to switch those imports for different environments.

Keeping only cjs requires bundlers to add runtime interop which increases result bundle size.

We may do the best of two worlds allow both ways. So main and module fields will refer to bundles, but users which do not use bundlers will consume files from paths.

**Comment by jquense** [comment]
we are having a similar discussion here: https://github.com/reactjs/react-transition-group/pull/77

**Comment by jquense** [comment]
on a technical note this seems to be incomplete, where and when is this run?

**Comment by TrySound** [comment]
About that issue. I don't beleive in wide adoption of mjs. It will just gone once. esm loads shows us that we don't need mjs to solve the problem.

**Comment by jquense** [comment]
I think ppl focusing on the `mjs` extension here is the wrong focus. the idea or concept is not to embrace some different thing or be on the bleeding edge of something, but lean on the behavior that already exists in the tools we are building for. 

re: this PR I don't love the asymmetry between the esm  and cjs build here. Tree-shaking is a less efficient and more error prone cherry-picking, I don't want it to be the only strategy for esm for dom-helpers since the spirit of this package is to allow efficient ultra modularization and importing only exactly what one needs. The flat esm build is likely to not produce that given (or break easily) give how much we depend on and write to globals. I'd be surprised if consuming builders don't deopt on treeshaking.

**Comment by TrySound** [comment]
What do you mean by "deopt on treeshaking"?

**Comment by jquense** [comment]
treeshaking can only be done against things with no side-effects, which is not something that is always statically determinable when looking at the code. If an import or export somewhere can't be proven to be pure the bundler has to assume it's not, and not remove the code. considering how much this library touches globals i think we have to see (and lint for) things being properly treeshook if someone does `import { matches } from 'dom-helpers'`

**Comment by TrySound** [comment]
Actually treeshaking it's not about pure functions. Side effect in treeshakable world is toplevel expression (calling global functions or mutating in toplevel). And size snapshot plugin allows to track this treeshakability.

Take a look here. It's simple trick to check how much top level mutations still exist. When we achieve 0 for rollup and ~560 for webpack (it's just webpack runtime) we can safely land flat bundle and be sure that user will treeshake out unused stuff.
https://github.com/react-bootstrap/dom-helpers/pull/42/files#diff-29fd455fe4a1c8d19c5e5b1420ce14faR6

**Comment by TrySound** [comment]
And I already achieved full treeshakability locally and would like to send these results step by step.

**Comment by TrySound** [comment]
I would like to have your review in each step. So maybe you could create a branch from master where to I will create PRs?

**Comment by TrySound** [comment]
`npm run rollup -c` / `yarn rollup -c` should work

**Comment by TrySound** [comment]
The problem is solved with `module` field in package.json. And `react-bootstrap` will import from `dom-helpers` (without any additional paths) and webpack will resolve and treeshake it. And it can be run in node, but `module` field does not exist for node and `main` field will be used instead.

**Comment by TrySound** [comment]
If every bundler is able to consume esm than cjs will be consumed only by node. So yeah node will load a bit more code. The final structure will look like this
```
{
  "main": "dist/dom-helpers.cjs.js",
  "module": "dist/dom-helpers.esm.js"
}
```

We are making sure in treeshakability in this project. `react-bootstrap` should care only its own code.

Scope hoisting with cjs will never work 100% because of javascript dynamism. In a lot of cases module should be wrapped with runtime.

Yeah, we just should consider that esm is required and path imports does not allow to solve the problem of choice easily. Single entry point adds more predictability and allow us do not care about file structure and do not introduce its changing as a breaking change.

**Comment by taion** [comment]
Given the options here, I don't think that using flat bundles is necessary for packages like this that target front-end use. I think the best approach for distributing such packages on npm right now might be to follow what `graphql` does, and ship both `.mjs` and `.js` files in the same directory: https://unpkg.com/graphql@0.13.2/type/.

In the context of front-end, webpack 4 will default to choosing the `.mjs` files, which will enable its own scope hoisting optimizations. If users trust tree-shaking, then they can use the top-level exports. For other applications, importing from nested paths will "just work", as `foo/lib/Bar` will resolve to `foo/lib/Bar.mjs`, which will be an ES module, and will be properly scope hoisted by the bundler.

In that sense, then, tree shaking is still possible when desired, but users aren't forced into trusting tree-shaking, especially in the context of "utility" libraries like this where any consumer may only use a small subset of the functionality available.

I think paradoxically, given this extension resolution support, the best case for distributing flat bundles might instead be libraries targeting Node for server-side use to optimize startup time. In any other case, there's going to be a bundler that can handle its own scope hoisting anyway.

**Comment by TrySound** [comment]
@taion Bundlers startup time is also important for dev process.

As I said mjs extension may just gone and we will be forces to find different ways to solve the problem.

You are talking about trust to treeshaking but I just gave you a tool to prove treeshaking by simply creating `import {} from 'lib'` bundle on the fly for both webpack and rollup. The problem of trust is solved.

`module` field is a solution which just works for a long time without changing semantics (and extensions).

Also if we provide a few different ways to solve the problem then libraries may choose different ways  so user bundle may become even bigger because of this.

**Comment by jquense** [comment]
> module field is a solution which just works for a long time without changing semantics (and extensions).

I really don't think this is anymore true than the `mjs` extension resolution. _both_ are completely up to the defaults set by webpack, and both are as "official", in that they are both arbitrary approaches  that webpack implements. Like the entire `module` main idea is part of the other node esm proposal. If anything its _more_ likely to go away, as that proposal is not winning and `mjs` is actually implemented in node. I think a conversation of about witch approach is more "official" is misguided and misses point since neither are official in any meaningful sense other than "the bundler everyone uses understands this"

> The problem of trust is solved.

Sure but wouldn't you agree not having the problem at all is preferable to having it and solving it? It feels like bending over backwards to add tooling when it's not necessary to get the same outcome

**Comment by TrySound** [comment]
Okay. Let's solve problems step by step. My first proposal is treeshakability of this project. Then you may chose whatever you want distibution. This flat bundle is used only for information.

I added `treeshake` npm script which generates size-snapshot with treeshakability information and do not generate any bundles.

**Comment by jquense** [comment]
Yes, sorry getting side tracked :) let's make the treeshaking excellent 👍this looks good to me

**Comment by TrySound** [comment]
@jquense Would be good if you will create a branch where I will create PRs.

**Pull request merged**
