### PR TITLE
Provide UMD bundle

### PR DESCRIPTION
**Pull request by TrySound**
UMD bundles are useful to play with library in sandboxes.

It also can help to track whole size of the library and optimize some
parts of it.

Here's exports assigned to `DomHelpers` global namespace

```js
var index = _extends({}, events, query, {
  style: style,
  activeElement: activeElement,
  ownerDocument: ownerDocument,
  ownerWindow: ownerWindow,
  requestAnimationFrame: requestAnimationFrame
});

exports.style = style;
exports.activeElement = activeElement;
exports.ownerDocument = ownerDocument;
exports.ownerWindow = ownerWindow;
exports.requestAnimationFrame = requestAnimationFrame;
exports.default = index;
exports.on = on$1;
exports.off = off$1;
exports.filter = filterEvents;
exports.listen = listen$1;
exports.matches = matches;
exports.height = height;
exports.width = width;
exports.offset = offset;
exports.offsetParent = offsetParent;
exports.position = position;
exports.contains = contains;
exports.scrollParent = scrollPrarent;
exports.scrollTop = scrollTop;
exports.querySelectorAll = qsa;
exports.closest = closest;

Object.defineProperty(exports, '__esModule', { value: true });
```

### CODE REVIEW

**Comment by jquense** [comment]
I've generally not included a UMD build because i don't really want to support that use-case (for anything other than plying around in jsfiddle anyway), the main point of the package is cherry pickable utilities. I actually regret even providing a `main` import since it encourages bad usage patterns. 

I do like being able to access it via unpkg tho...

**Comment by TrySound** [comment]
`main` field is not a problem. When we will achieve treeshaking it won't be a bad pattern. Just an alternative. And yes, I unpkg is great for this. Providing a bunch of umd only complicates usage so I don't think any sense in it. We still do not provide minified version so it should be used only for development stuff.

**Comment by TrySound** [comment]
My point is size tracking. unpkg in sandboxes is another one. Isn't it enough?

**Comment by jquense** [comment]
@TrySound if you want to fix this up, i'll merge this in

**Comment by TrySound** [comment]
its not very relevant for me. do you think it can be useful?

**Comment by jquense** [comment]
I don't feel very strongly either way. Would be nice to see if tree-shaking is working I guess?

**Comment by TrySound** [comment]
another config is required then. will sibmit another pr

**Pull request closed without merging**
