### PR TITLE
fix scrollbarSize and add karma test for firefox

### PR DESCRIPTION
**Pull request by amarant**
fix scrollbarSize when recalc is falsy and size undefined and add karma testing for firefox add travis support

### CODE REVIEW

**Comment by jquense** [comment]
Hi there, thanks for the the PR. There is a bit of a concern here as this conflicts with what was done in: https://github.com/react-bootstrap/dom-helpers/pull/21

**Comment by amarant** [comment]
I thought I had taken it into this commit, but now I think I  understood it the opposite way, so the goal was to cache the size if it was 0, but why the test `size !== undefined` ? It means that with the `let size` it will be `undefined`. So i'm going to remove the test `size === 0`.

**Comment by jquense** [comment]
hmm yeah, it really should be any falsey value that isn't `0` so `(!size && size !== 0) || recalc`

**Comment by amarant** [comment]
I agree, done !

**Comment by jquense** [comment]
Thanks!

**Comment by amarant** [comment]
Could you push an update to npm so I can fix the firefox errors in react-overlays ?

**Pull request merged**
