### PR TITLE
Treeshake events by lazy caching

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Why? Is it slow?

**Comment by TrySound** [comment]
Is it slow enough to not consider this change? How often `on` and `off` could be called?

**Comment by TrySound** [comment]
Do you think this simple check will slowdown your app? No, rollup does not support it.

**Comment by TrySound** [comment]
@jquense What's your opinion?

**Comment by jquense** [comment]
I think from a performance standpoint it's probably ok but thats a guess. In general tho this sort of change is a good indication of my (our) concern with relying on treeshaking. This feels like a really arbitrary change from the outside and it's not at all clear why it would be written like this vs the existing code. Someone is likely to attempt to change this back unknowingly in the future, seeing an obvious place where less work could be done. Overall i'm less concerned about perf here than the increased maintenance burden.

**Comment by TrySound** [comment]
If you won't remove size-snapshot the idea will be very clear. Actually you already use this idea [here](https://github.com/react-bootstrap/dom-helpers/blob/master/src/query/matches.js#L5). The reason is lazy evaluation which makes browser api accessing time more predictable and as a result polyfillable however not sure if this makes sense for this liv.

**Comment by TrySound** [comment]
I think I could fork the package.

**Comment by jquense** [comment]
Sorry the process hasn't been fast enough. We have very limited time and slight build optimizations, while very appreciated, aren't high on the priority list for those of us maintaining

**Comment by jquense** [comment]
this is all going into a separate branch, so lets just get it in and see what it looks like all at the end. Sorry the for the slow response we're both pretty busy these days.

**Pull request merged**
